id: P009347
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN3397
  title: དབུ་མ་ལ་འཇུག་པའི་བཤད་པ།
  author: ''
  volumes:
    fd06ea03d99a46019c7532656bdccb1f:
      image_group_id: I3CN8566
      title: ''
      volume_number: 1
      total_pages: 276
